apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: te-cpu
  name: te-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: te-cpu
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: te-cpu
    spec:
      containers:
        - image: te-cpu
          name: te-cpu
          imagePullPolicy: Never
          ports:
            - containerPort: 9010
          resources:
            limits:
              cpu: 500m
              memory: "67108864"
      restartPolicy: Always
status: {}
