apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: te-memory
  name: te-memory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: te-memory
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: te-memory
    spec:
      containers:
        - image: te-memory
          name: te-memory
          ports:
            - containerPort: 9010
          resources:
            limits:
              cpu: "1"
              memory: "16777216"
      restartPolicy: Always
      imagePullPolicy: never
status: {}
